### ISSUE TITLE
Add Connection Recovery

### ISSUE THREAD

**Issue by brownc** [ExpediaDotCom/seiso-import_chef#9]
Currently we have a default timeout, and if a connection is dropped we get something like this:

/home/{ME}/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/http.rb:923:in `connect': Connection reset by peer - SSL_connect (Errno::ECONNRESET)
	from /home/chrbrown/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/http.rb:923:in `block in connect'
	from /home/chrbrown/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/timeout.rb:89:in `block in timeout'
	from /home/chrbrown/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/timeout.rb:99:in `call'
	from /home/chrbrown/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/timeout.rb:99:in `timeout'
	from /home/chrbrown/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/http.rb:923:in `connect'
	from /home/chrbrown/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
	from /home/chrbrown/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/http.rb:852:in `start'
	from /home/chrbrown/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/http.rb:1374:in `request'
	from /home/chrbrown/.rvm/gems/ruby-2.2.0/gems/chef-12.3.0/lib/chef/http/basic_client.rb:65:in `request'

At this point the whole job barfs, just because we've hit an issue with 1 node.

We should look to do something similar to the following:

1) Add a retry when a connection fails (potentially 2)
2) Optionally set a threshold for the entire script that says number of errors we can accept before we die

With both of these in place, if we have 1000 servers to import, and we get a timeout/reset every 100 or so connections, that's not great, but it's not the end of the world.  Without point 2 however, we'd spend about 8h25 wasting resource before the job fails, as opposed to say failing after 50 errors in total, which would be still a few mins, not hours before job failure.

Once my current pushes are reviewed, happy to work on this.

**Comment by williewheeler** [comment]
This would be nice to have for the other connectors too.

**Comment by brownc** [comment]
Small steps - I'll prioritise the chef-importer, and then take the same code into our other importers as well have no fear.
